extends SceneTree

func _init() -> void:
	assert(BrokenGameData.MONSTERS.size() == 21)
	assert(BrokenGameData.RELICS.size() == 32)
	assert(BrokenGameData.POTIONS.size() == 6)
	assert(BrokenGameData.MAGIC_ARMORS.size() == 4)
	for id in BrokenGameData.MONSTERS:
		var monster := BrokenGameData.make_monster(id)
		assert(monster.current_hp == monster.max_hp)
		assert(not monster.attacks.is_empty())
	for id in BrokenGameData.RELICS:
		assert(BrokenGameData.make_relic(id).name != "")
	assert(BrokenGameData.CHARACTERS.size() == 3)
	assert(BrokenGameData.MAGE_SPELLS.size() == 6)
	var game := BrokenGameState.new()
	var menu := game.main_menu()
	assert(menu.actions.size() == 2)
	assert(game.phase == "MAIN_MENU")
	var select := game.start_new_game()
	assert(select.actions.size() == 3)
	assert(game.phase == "CHARACTER_SELECT")
	var start := game.start_new_game("warrior")
	assert(start.actions.size() == 5)
	assert(game.player.class_id == "warrior")
	assert(game.current_floor == 1)
	var combat := game.start_combat(["LostSoul"], false)
	assert(combat.actions.size() == 5)
	var targets := game.select_target("attack")
	assert(targets.actions.size() == 2)
	var guarded := game.defend()
	assert(guarded.get("next_action", "") == "enemy_turn")
	var enemy_result := game.enemy_turn()
	assert(not enemy_result.actions.is_empty())
	game.level_up("armor")
	assert(game.current_floor == 2)
	game.level_up("warrior_shield")
	assert(game.current_floor == 3)
	var warrior_rewards := BrokenGameState.new()
	warrior_rewards.start_new_game("warrior")
	var warrior_actions := warrior_rewards.boss_reward_actions()
	assert(warrior_actions.size() == 3)
	assert(warrior_actions[0].args.kind == "armor")
	assert(warrior_actions[1].args.kind == "vitality")
	assert(warrior_actions[2].args.kind == "warrior_shield")
	warrior_rewards.level_up("warrior_shield")
	warrior_rewards.level_up("armor")
	assert(warrior_rewards.player.temp_hp == 6)
	var vitality_rewards := BrokenGameState.new()
	vitality_rewards.start_new_game("warrior")
	vitality_rewards.player.current_hp = 1
	vitality_rewards.level_up("vitality")
	assert(vitality_rewards.player.max_hp == 33)
	assert(vitality_rewards.player.current_hp == 27)
	var forsaken_warrior := BrokenGameState.new()
	forsaken_warrior.start_new_game("warrior")
	assert(forsaken_warrior.boss_victory([]).actions.size() == 4)
	forsaken_warrior.level_up("forsake_boss_reward")
	assert(forsaken_warrior.player.forsook_first_boss_reward)
	assert(forsaken_warrior.current_floor == 2)
	var warrior_legend := forsaken_warrior.boss_victory([])
	assert(warrior_legend.actions.size() == 1)
	assert(warrior_legend.actions[0].args.kind == "legendary_warrior")
	var special_boss := BrokenGameState.new()
	special_boss.start_new_game("warrior")
	special_boss.current_floor = 2
	special_boss.player.forsook_first_boss_reward = true
	special_boss.start_combat(["MemoryKeeper"], true)
	var special_boss_reward := special_boss.victory([])
	assert(special_boss_reward.actions.size() == 1)
	assert(not special_boss_reward.logs.any(func(line): return "发现遗物" in line))
	forsaken_warrior.level_up("legendary_warrior")
	forsaken_warrior.start_combat(["LostSoul"], false)
	assert(forsaken_warrior.gain_shield(5, []) == 10)
	forsaken_warrior.player.temp_hp = 0
	forsaken_warrior.apply_damage(1)
	assert(forsaken_warrior.player.warrior_wound_ac_ready)
	var boss_game := BrokenGameState.new()
	boss_game.start_new_game("warrior")
	boss_game.current_floor = 4
	boss_game.start_combat(["ZhongMoBenShen"], true)
	boss_game.combat_round = 3
	boss_game.pending_enemies = boss_game.enemies.duplicate()
	assert(not boss_game.enemy_turn().is_empty())
	var mage := BrokenGameState.new()
	assert(mage.start_new_game().actions.size() == 3)
	mage.start_new_game("mage")
	assert(mage.player.class_id == "mage")
	assert(mage.player.intelligence == 18)
	assert(mage.player.max_hp == 25)
	assert(mage.boss_reward_actions()[2].args.kind == "mage_charge")
	mage.level_up("mage_charge")
	var mage_combat := mage.start_combat(["LostSoul"], false)
	assert(mage_combat.actions.size() == 5)
	assert(mage_combat.actions[2].disabled)
	assert(mage.player.charge == 1)
	var forsaken_mage := BrokenGameState.new()
	forsaken_mage.start_new_game("mage")
	forsaken_mage.level_up("forsake_boss_reward")
	assert(forsaken_mage.boss_victory([]).actions[0].args.kind == "legendary_mage")
	forsaken_mage.level_up("legendary_mage")
	forsaken_mage.start_combat(["LostSoul"], false)
	assert(forsaken_mage.mage_defense_retry_available)
	var spellsword := BrokenGameState.new()
	spellsword.start_new_game("spellsword")
	assert(spellsword.player.class_id == "spellsword")
	assert(spellsword.player.max_hp == 26)
	assert(spellsword.boss_reward_actions()[2].args.kind == "spellsword_ritual")
	spellsword.level_up("spellsword_ritual")
	var spellsword_combat := spellsword.start_combat(["LostSoul"], false)
	assert(spellsword_combat.actions.size() == 5)
	assert(spellsword.magic_armors.size() == 1)
	assert(spellsword.magic_armors[0].turns == 3)
	var ritual := spellsword.magic_armor_ritual()
	assert(spellsword.player.current_hp == 26)
	assert(not spellsword.magic_armor_ritual_free_available)
	assert(spellsword.phase == "MAGIC_ARMOR_SELECT")
	assert(ritual.actions.size() == 4)
	spellsword.equip_magic_armor("hunter")
	assert(spellsword.magic_armors.size() == 2)
	assert(spellsword.magic_armors.any(func(armor): return armor.id == "hunter"))
	assert(spellsword.magic_armor_roll_bonus >= 1)
	spellsword.end_enemy_turn()
	assert(spellsword.magic_armors.size() == 2)
	assert(spellsword.magic_armors.all(func(armor): return armor.turns == 2))
	spellsword.pending_defense = {"roll":10, "damage":4}
	spellsword.phase = "COMBAT_DEFEND"
	spellsword.resolve_magic_dodge()
	assert(spellsword.magic_dodge_cooldown == 2)
	var legendary_spellsword := BrokenGameState.new()
	legendary_spellsword.start_new_game("spellsword")
	legendary_spellsword.level_up("forsake_boss_reward")
	assert(legendary_spellsword.boss_victory([]).actions[0].args.kind == "legendary_spellsword")
	legendary_spellsword.level_up("legendary_spellsword")
	legendary_spellsword.start_combat(["CerberusPup"], false)
	assert(legendary_spellsword.magic_armors.size() == 2)
	legendary_spellsword.apply_magic_armor("hunter", [])
	assert(legendary_spellsword.magic_armors.back().damage >= 2)
	assert(legendary_spellsword.magic_armors.back().damage <= 4)
	var ritual_result := legendary_spellsword.magic_armor_ritual()
	assert(ritual_result.logs.any(func(line): return "DC14" in line))
	legendary_spellsword.player.current_hp = 10
	legendary_spellsword.victory([])
	assert(legendary_spellsword.player.current_hp == 11)
	mage.player.charge = 0
	mage.arcane_torrent()
	assert(mage.player.charge == 3)
	var spell_options := mage.spell_slot()
	assert(spell_options.actions.size() == 4)
	mage.mage_spells = [BrokenGameData.mage_spell("void_barrier")]
	var cast := mage.cast_spell("void_barrier")
	assert(mage.player.used_spell_ids == ["void_barrier"])
	assert(mage.player.charge == 0)
	assert(mage.player.temp_hp >= 20)
	assert(cast.get("next_action", "") == "enemy_turn")
	var counter_mage := BrokenGameState.new()
	counter_mage.start_new_game("mage")
	counter_mage.start_combat(["LostSoul"], false)
	counter_mage.pending_defense = {"roll":99, "damage":4}
	counter_mage.resolve_energy_counter()
	assert(counter_mage.player.charge == 1)
	var barrier_mage := BrokenGameState.new()
	barrier_mage.start_new_game("mage")
	barrier_mage.start_combat(["LostSoul"], false)
	barrier_mage.player.charge = 1
	barrier_mage.pending_defense = {"roll":10, "damage":0}
	barrier_mage.resolve_arcane_barrier()
	assert(barrier_mage.player.charge == 0)
	assert(barrier_mage.player.temp_hp == 6)
	var starfall_mage := BrokenGameState.new()
	starfall_mage.start_new_game("mage")
	starfall_mage.start_combat(["LostSoul"], false)
	starfall_mage.player.charge = 3
	starfall_mage.resolve_spell(BrokenGameData.mage_spell("starfall"), starfall_mage.enemies[0])
	assert(not starfall_mage.alive(starfall_mage.enemies[0]))
	var field_mage := BrokenGameState.new()
	field_mage.start_new_game("mage")
	field_mage.start_combat(["LostSoul"], false)
	field_mage.player.charge = 3
	field_mage.resolve_spell(BrokenGameData.mage_spell("absolute_field"), {})
	assert(field_mage.player.ac == 17)
	var siphon_mage := BrokenGameState.new()
	siphon_mage.start_new_game("mage")
	siphon_mage.start_combat(["CerberusPup"], false)
	siphon_mage.player.charge = 3
	siphon_mage.resolve_spell(BrokenGameData.mage_spell("arcane_siphon"), siphon_mage.enemies[0])
	assert(siphon_mage.player.temp_hp >= 10)
	var revival_mage := BrokenGameState.new()
	revival_mage.start_new_game("mage")
	revival_mage.start_combat(["LostSoul"], false)
	revival_mage.player.current_hp = 5; revival_mage.player.charge = 3
	revival_mage.resolve_spell(BrokenGameData.mage_spell("echo_revival"), {})
	assert(revival_mage.player.current_hp == 13)
	assert(revival_mage.player.temp_hp >= 10)
	var curse_mage := BrokenGameState.new()
	curse_mage.start_new_game("mage")
	curse_mage.start_combat(["LostSoul", "WindborneLust"], false)
	curse_mage.player.charge = 3
	curse_mage.resolve_spell(BrokenGameData.mage_spell("disorder_curse"), {})
	assert(curse_mage.enemies[0].ac == 8)
	assert(curse_mage.enemies[0].combat_attack_penalty == 3)
	assert(curse_mage.enemies[1].ac == 11)
	assert(curse_mage.enemies[1].combat_attack_penalty == 3)
	var multi_slot_mage := BrokenGameState.new()
	multi_slot_mage.start_new_game("mage")
	multi_slot_mage.start_combat(["CerberusPup"], false)
	multi_slot_mage.mage_spells = [BrokenGameData.mage_spell("void_barrier"), BrokenGameData.mage_spell("absolute_field"), BrokenGameData.mage_spell("echo_revival")]
	for spell_id in ["void_barrier", "absolute_field", "echo_revival"]:
		multi_slot_mage.player.charge = 3
		multi_slot_mage.cast_spell(spell_id)
	assert(multi_slot_mage.player.used_spell_ids.size() == 3)
	assert(multi_slot_mage.spell_slot().actions[2].disabled)
	var event_game := BrokenGameState.new()
	event_game.start_new_game("warrior")
	event_game.current_floor = 3
	event_game.distance_to_boss = 8
	var third_floor_map := event_game.generate_explore()
	assert(third_floor_map.actions.any(func(action): return action.id == "third_floor_event"))
	var event_choice := event_game.third_floor_event()
	assert(event_game.phase == "THIRD_FLOOR_EVENT")
	assert(event_choice.actions.size() == 2)
	event_game.player.current_hp = 10
	event_game.third_floor_heal()
	assert(event_game.player.current_hp == 15)
	assert(event_game.player.third_floor_event_used)
	var skip_game := BrokenGameState.new()
	skip_game.start_new_game("mage")
	skip_game.current_floor = 3
	var skip_result := skip_game.skip_to_third_boss()
	assert(skip_game.player.third_floor_event_used)
	assert(skip_game.phase == "COMBAT_PLAYER")
	assert(skip_game.enemies.size() == 1)
	assert(skip_game.enemies[0].id == "CanYiShouMenRen")
	assert(not skip_result.actions.is_empty())
	var potion_game := BrokenGameState.new()
	potion_game.start_new_game("warrior")
	potion_game.start_combat(["LostSoul"], false)
	potion_game.player.current_hp = 10
	for potion_id in ["healing", "might", "precision", "weakening", "barrier", "fire"]:
		potion_game.player.items.append(BrokenGameData.make_potion(potion_id))
	assert(potion_game.show_item_selection().actions.size() == 13)
	potion_game.use_item(0)
	assert(potion_game.player.current_hp == 15)
	potion_game.show_item_selection(); potion_game.use_item(0)
	assert(potion_game.combat_damage_bonus == 1)
	potion_game.show_item_selection(); potion_game.use_item(0)
	assert(potion_game.combat_attack_roll_bonus == 2)
	potion_game.show_item_selection(); potion_game.use_item(0)
	assert(potion_game.combat_enemy_attack_penalty == 2)
	potion_game.show_item_selection(); potion_game.use_item(0)
	assert(potion_game.player.temp_hp == 8)
	potion_game.show_item_selection(); potion_game.use_item(0)
	assert(potion_game.phase == "ITEM_TARGET")
	potion_game.use_item_target(0)
	assert(potion_game.player.items.is_empty())
	assert(not potion_game.alive(potion_game.enemies[0]))
	var pickup_game := BrokenGameState.new()
	pickup_game.start_new_game("warrior")
	var pickup := pickup_game.offer_potion_pickup(BrokenGameData.make_potion("healing"), "treasure", [])
	assert(pickup_game.phase == "POTION_PICKUP")
	assert(pickup.actions.size() == 2)
	pickup_game.execute_action("pickup_item")
	assert(pickup_game.player.items.size() == 1)
	var inventory_game := BrokenGameState.new()
	var inventory_map := inventory_game.start_new_game("warrior")
	assert(inventory_map.actions.any(func(action): return action.id == "items"))
	inventory_game.player.items.append(BrokenGameData.make_potion("healing"))
	var inventory := inventory_game.show_item_selection()
	assert(inventory.actions.size() == 2)
	inventory_game.drop_inventory_item(0)
	assert(inventory_game.player.items.is_empty())
	var full_inventory_game := BrokenGameState.new()
	full_inventory_game.start_new_game("warrior")
	for potion_id in ["healing", "might", "precision"]:
		full_inventory_game.player.items.append(BrokenGameData.make_potion(potion_id))
	var full_pickup := full_inventory_game.offer_potion_pickup(BrokenGameData.make_potion("barrier"), "treasure", [])
	assert(full_pickup.actions[0].disabled)
	full_inventory_game.execute_action("pickup_item")
	assert(full_inventory_game.player.items.size() == BrokenGameState.MAX_POTION_SLOTS)
	var penalty_game := BrokenGameState.new()
	penalty_game.start_new_game("warrior")
	penalty_game.start_combat(["LostSoul"], false)
	penalty_game.player.items.append(BrokenGameData.make_potion("weakening"))
	penalty_game.show_item_selection(); penalty_game.use_item(0)
	penalty_game.schedule_enemy([])
	var weakened_attack := penalty_game.enemy_turn()
	assert(weakened_attack.logs.any(func(line): return line.contains("削弱来源：灰雾削弱药剂 -2")))
	print("Broken smoke test passed")
	quit()
